### ISSUE TITLE
ロケット記法はRuby1.8時代の書き方のためシンボル表記に書き換えてください

### ISSUE THREAD

**Issue by norotime** [tkgs0109/DIC_scripting_task#1]
https://github.com/tkgs0109/DIC_scripting_task/blob/3031b4878fbe55461397d514c72823714d6ee444/app/controllers/tasks_controller.rb#L6

**Comment by norotime** [comment]
@tkgs0109 シンボルを使うメリットは下記です。

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない

**Comment by norotime** [comment]
@tkgs0109 
=> ではなく : で表記しましょう！

**Comment by tkgs0109** [comment]
対応しました。
こういった、エラーではないしちゃんと動くが今はもう古いから使わない、といったご指摘は、自分では気づけないものなので大変為になりました。

**Comment by norotime** [comment]
@tkgs0109 他にもないか全てチェックしてください。

**Comment by tkgs0109** [comment]
grepコマンドにてチェックいたしました！
