### ISSUE TITLE
文字列よりもシンボルの方が高速なため書き換える

### ISSUE THREAD

**Issue by norotime** [tkgs0109/DIC_scripting_task#4]
https://github.com/tkgs0109/DIC_scripting_task/blob/3031b4878fbe55461397d514c72823714d6ee444/app/controllers/tasks_controller.rb#L53

シンボルを使うメリットは

新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない

です。

**Comment by tkgs0109** [comment]
修正しました。
