### ISSUE TITLE
コミットメッセージでイシューをクローズする方法を理解する

### ISSUE THREAD

**Issue by norotime** [tkgs0109/DIC_scripting_task#9]
@tkgs0109 https://help.github.com/articles/closing-issues-using-keywords/

**Comment by norotime** [comment]
@tkgs0109 この方法でイシューを全て消化してくださいーー。

**Comment by tkgs0109** [comment]
@norotime 承知いたしました！

**Comment by tkgs0109** [comment]
理解したのでクローズします。
コミットメッセージ/プルリクのメッセージでこういった操作ができるのは初めて知りました。

**Comment by norotime** [comment]
@tkgs0109 使いこなしてください。
